apiVersion: v1
kind: Service
metadata:
  labels:
    api: wordpress
  name: wordpress
spec:
  externalTrafficPolicy: Local
  ports:
  - nodePort: 30327
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress       
    tier: frontend
  type: LoadBalancer
